name: Check
on: pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run depcheck
      - run: |
          yarn run lint
      - run: |
          yarn run ncu
